### ISSUE TITLE
Lost a "h" in the prefix "https"

### ISSUE THREAD

**Issue by dxyzx0** [RoiArthurB/Side-Auto_Sci-Hub#12]
**Describe the bug**
Click auto sci-hub on every link will give a wrong url, which loses a leading "h".

**To Reproduce**
If you click auto sci-hub in latest firefox:
`https://www.sciencedirect.com/science/article/abs/pii/S0927050789010054`
The url in new tab is 
`https://sci-hub.se//ttps%3A%2F%2Fwww.sciencedirect.com%2Fscience%2Farticle%2Fabs%2Fpii%2FS0927050789010054`
without a leading 'h'.

**Expected behavior**
The url in new tab should be
`https://sci-hub.se//https%3A%2F%2Fwww.sciencedirect.com%2Fscience%2Farticle%2Fabs%2Fpii%2FS0927050789010054`

**Screenshots**
![Snipaste_2020-01-07_20-01-52](https://user-images.githubusercontent.com/28868457/71894216-9bf41780-3188-11ea-9491-3f7face5f3b2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser : Firefox
 - Version : 71.0 (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RoiArthurB** [comment]
> **Describe the bug**
Click auto sci-hub on every link will give a wrong url, which loses a leading "h".

Turning the _h_ in _slash_ in the redirected Sci-Hub URL
```
https:// => ../ttps://
```

> **Expected behavior**
The URL in new tab should be `https://sci-hub.se//https%3A%2F2Fwww.sciencedirect.com%2Fscience%2Farticle%2Fabs%2Fpii%2FS0927050789010054`

The URL should be as follow : https://sci-hub.se/https://www.sciencedirect.com/science/article/abs/pii/S0927050789010054 (single slash after sci-hub)

**Possibles causes**
* [ ] WhereIsSciHub => Waiting to apply the [PR](https://gitlab.com/Flockademic/whereisscihub/merge_requests/4)
* [ ] Preprocessing URL => Removing the `escape(..)` js usage

**Comment by bobackz** [comment]
I have the same new problem.

**Comment by nevillepark** [comment]
This is also happening for me.

**Comment by RoiArthurB** [comment]
Should be fixed there eb85044
Wait until I push it on store :)

**Comment by RoiArthurB** [comment]
The bug remains because of WhereIsSciHub... I'm working on adding options to use the redirect url of your choice (when @Vinnl will merge my PR, the plugin will be working fine again !)

**Comment by VictorAlexanderMa** [comment]
Sorry, this bug remains in the latest version 1.7.
When I browse the paper I want in a tab and click the auto sci-hub button, the redirect URL of this paper is still wrong with a deficiency of "h". I can correctly view this paper in that new tap after I add an "h" in the redirect URL. The screenshots of the problem I meet are here. Hope this bug can be fixed. Thanks! @RoiArthurB 
![图片](https://user-images.githubusercontent.com/48207347/73327723-02ed8380-4292-11ea-9ce1-2474ba5da82a.png)
![图片](https://user-images.githubusercontent.com/48207347/73327598-9a9ea200-4291-11ea-94e3-a8996ad58457.png)
![图片](https://user-images.githubusercontent.com/48207347/73327650-c9b51380-4291-11ea-84ec-39145ecb210a.png)

**Comment by RoiArthurB** [comment]
Hi @VictorAlexanderMa 
I'm aware of this bug, the problem comes from the  WISH ( WhereIsSciHub ) redirection which preprocess the URL and, because of an SH update of their architecture, that redirect doesn't work anymore... I did a PR to WISH to fix it but... I'm waiting for several months now... :/

The problem is that if I explicitly gather SH URLs in the plugin I'm afraid to not respect the Firefox's rules and having my plugin being struck :/

So, what I'm currently working on is to create an option to change your default server redirector (the idea is that the WISH code is open and you can freely create your own on Zeit (and it will be automatically updated) ) and to let everyone put whatever they want ( a raw IP address, a redirector, etc etc)

If you have a better solution feel free to propose, but for now that's what I'm working on (and the only solution I founded) :bear:

**Comment by RoiArthurB** [comment]
Fixed in 8580392 and c7976e0
